name: Fetch Dexcom Data

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    env:
      DEXCOM_USERNAME: ${{ secrets.DEXCOM_USERNAME }}
      DEXCOM_PASSWORD: ${{ secrets.DEXCOM_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pydexcom
        run: pip install pydexcom

      - name: Run Dexcom script
        run: python3 bin/fetch_dexcom.py

      - name: Commit and push if it changed
          run: |-
            git config user.name "Automated"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            timestamp=$(date -u)
            git commit -m "Latest data: ${timestamp}" || exit 0
            git push