name: Fetch Dexcom Data

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pydexcom
        run: pip install pydexcom

      - name: Run Dexcom script
        env:
          DEXCOM_USERNAME: ${{ secrets.DEXCOM_USERNAME }}
          DEXCOM_PASSWORD: ${{ secrets.DEXCOM_PASSWORD }}
        run: python3 bin/fetch_dexcom.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        shell: bash

      - name: Commit changes
        run: >
          git add -A &&
          (git diff --cached --quiet || (git commit -m "Automated data run" && git push))

